language: ruby
rvm:
  - 2.1.1

# whitelist
branches:
  only:
    - master
    - demo
    - dev

addons:
  postgresql: "9.2"

script:
  - RAILS_ENV=test bundle exec rake secret
  - RAILS_ENV=test bundle exec rake --trace db:migrate spec

before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.yml.sample config/secrets.yml
  - psql -c 'create database canseidovermelho_test;' -U postgres
