language: ruby
cache: bundler
bundler_args: --without guard --deployment
rvm:
  - 2.2.4

# whitelist
branches:
  only:
    - master
    - demo
    - dev

addons:
  postgresql: "9.2"

script:
  - RAILS_ENV=test bundle exec rake --trace secret db:migrate spec

before_script:
  - cp config/secrets.yml.sample config/secrets.yml
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database canseidovermelho_test;' -U postgres
